### ISSUE TITLE
Speed of fine-tuning NASNet

### ISSUE THREAD

**Issue by nasusu** [Cadene/pretrained-models.pytorch#19]
First thanks for your pretrained model, it helps me a lot!

I try to fine-tune NASNet in my own dataset, but it seems to be very slow. It takes 10 second to go over a batch of size 8 in TitanX, almost 15 times slower than InceptionResnetV2. Is it normal？

**Comment by Cadene** [comment]
With the current version of pytorch, cudnn 7 and cuda 8 on a GTX 1070, it took 3 seconds just to do a forward pass over a batch of 50 images.

I installed the last pytorch version from master and it takes now 1.5 seconds. It is due to a better implementation of the separable convolutions.

I will try to do some benchmarks against the tensorflow implementation.

**Comment by nasusu** [comment]
What about training? Since I want to fine-tune the network, backward is essential. How long should it take to train a batch in common?

**Comment by Cadene** [comment]
@nasusu

For a forward + backward + optim pass on a single TITAN X Maxwell with CUDA8.0:

With batch of 3 images:

- pytorch 0.1.12_1 (max batch capacity): ~23 seconds
- pytorch 0.2.0_2: ~6.5 seconds
- pytorch 0.3.0.post4: ~0.5 seconds

With batch of 10 images:

- pytorch 0.2.0_2 (max batch capacity): ~8.1 seconds
- pytorch 0.3.0.post4 (max batch capacity): ~1.35 seconds


I am going to update this post (maybe adding CUDA9.0 and tensorflow).

**Comment by nasusu** [comment]
Thanks for your test!
