### ISSUE TITLE
How to remove the last 2 layers from caffe resnet-101, and build the new model

### ISSUE THREAD

**Issue by ShiKangdi** [Cadene/pretrained-models.pytorch#75]
Hello, I removed the last 2 layers in caffe resnet-101, and use following code to build new model for feature extraction.

model = pretrainedmodels.__dict__['cafferesnet101'](num_classes=1000, pretrained='imagenet')
newmodel = list(model.children())[:-2]
newmodel = nn.Sequential(*newmodel)

but I can't use tf_img = utils.TransformImage(newmodel) for that, which gives me the error:

AttributeError: 'Sequential' object has no attribute 'input_size'

*************************************************************************************************************

And I also don't want resize the image, just do to tensor, and normalize the image on cuda, like pytorch.

does this caffe model also need the input to be within [0~1], and normalize by using mean=[0.485, 0.456, 0.406],std=[0.229, 0.224, 0.225]?

Please help me, thank you very very much!

**Comment by Cadene** [comment]
You need to wrap it in order to overwrite the forward method.
https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/models/cafferesnet.py#L143

Our pretrained parameters need this kind of normalization:
https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/models/cafferesnet.py#L14

Range between 0-255

Different mean https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/models/cafferesnet.py#L14

No std
